language: node_js
node_js:
- 8
cache:
  directories:
    - "node_modules"
before_install:
- npm install
install:
- npm install
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: f251b456dc58f37e50183770fd94e9e71f56237d # Set in travis-ci.org dashboard
  on:
    branch: master